// Mocks generated by Mockito 5.4.0 from annotations
// in pomodoro_timer/test/timer/presentation/bloc/timer/timer_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pomodoro_timer/core/exceptions/failures.dart' as _i5;
import 'package:pomodoro_timer/core/success.dart' as _i8;
import 'package:pomodoro_timer/timer/domain/entity/timer_entity.dart' as _i6;
import 'package:pomodoro_timer/timer/domain/usecase/add_storage_timer.dart'
    as _i9;
import 'package:pomodoro_timer/timer/domain/usecase/get_timer.dart' as _i3;
import 'package:pomodoro_timer/timer/domain/usecase/set_timer.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetTimerUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTimerUsecase extends _i1.Mock implements _i3.GetTimerUsecase {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.TimerEntity>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.TimerEntity>>.value(
            _FakeEither_0<_i5.Failure, _i6.TimerEntity>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.TimerEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.TimerEntity>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.TimerEntity>>);
}

/// A class which mocks [SetTimerUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetTimerUsecase extends _i1.Mock implements _i7.SetTimerUsecase {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.Success>> call({
    int? pomodoroTime,
    int? breakTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #pomodoroTime: pomodoroTime,
            #breakTime: breakTime,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.Success>>.value(
            _FakeEither_0<_i5.Failure, _i8.Success>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #pomodoroTime: pomodoroTime,
              #breakTime: breakTime,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i8.Success>>.value(
                _FakeEither_0<_i5.Failure, _i8.Success>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #pomodoroTime: pomodoroTime,
              #breakTime: breakTime,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.Success>>);
}

/// A class which mocks [AddStorageTimerUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddStorageTimerUsecase extends _i1.Mock
    implements _i9.AddStorageTimerUsecase {
  @override
  void call(_i6.TimerEntity? timer) => super.noSuchMethod(
        Invocation.method(
          #call,
          [timer],
        ),
        returnValueForMissingStub: null,
      );
}
